matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      services:
        - mysql
      env:
        -DB_USER=root
      before_script:
        - cd api
        - npm install
        - npm run create_db
      script:
        - npm run migrate_db
        - npm run seed_db

    - language: javascript
      before_script:
        - cd view-app
      script:
        - yarn